
diffusion:
  # diffusion_steps_range: [0,1,2,3,4,5,6,7,8,9,10] # Diffusion steps to apply optimization
  diffusion_steps_range: [0,1,2,3] # Diffusion steps to apply optimization

optimization:
  update_per_step: 10  # Number of updates per denoise steps
  pearson_threshold: 0.9  # Pearson threshold 
  lr: 0.001  # Learning rate for optimization
  penalty_weight: 1  # Weight for the spatial consistency penalty term in the loss function
  energy_weight: 1 # Weight for the entropy term in the loss function
  entropy_weight: 10  # Weight for the entropy term in the loss function
  pearson_weight: 1
  optimize_two: true  # Whether to optimize two control signal at once, if false optimize just the first
  correlation_based_steps: true  # Whether to to stop early if the pearson exceeds the threshold